phases:
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t nginx ."
      - "docker tag nginx:latest 387118198074.dkr.ecr.us-west-1.amazonaws.com/demoecr:latest"
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 387118198074.dkr.ecr.us-west-1.amazonaws.com/demoecr:latest"
  pre_build:
    commands:
      - "echo Logging in to Amazon ECR..."
      - "$(aws ecr get-login --region us-west-1)"
version: 0.1
